// OrderService.ts - Complete order and payment flow
import { cartState } from "../state";


const BASE_URL = "http://localhost:8080/api";

// =====================================================
// ORDER DATA TYPES
// =====================================================

export type OrderItem = {
  productId: string;
  productType: string;
  quantity: number;
  customization: {
    color: string;
    decal: string;
    decalPosition: [number, number, number] | null;
    rotationY: number;
    ripples: { id: number; pos: [number, number, number] }[];
  };
  pricePerUnit?: number; // Optional: if you have pricing
};

export type Order = {
  orderId?: string; // Generated by backend
  items: OrderItem[];
  totalQuantity: number;
  totalPrice?: number; // Optional: if you have pricing
  customerInfo?: {
    email?: string;
    name?: string;
  };
  status: "pending" | "processing" | "completed" | "failed";
  createdAt?: string;
  paymentIntentId?: string; // Stripe payment intent ID
};

export type CheckoutSessionResponse = {
  sessionId: string;
  checkoutUrl: string;
  orderId: string;
};

// =====================================================
// PREPARE ORDER FROM CART
// =====================================================

/**
 * Converts cart items to order format
 */
export function prepareOrderFromCart(): Order {
  const orderItems: OrderItem[] = cartState.items.map((item) => ({
    productId: item.id,
    productType: item.selected_type,
    quantity: (item as any).quantity || 1,
    customization: {
      color: item.selectedColor,
      decal: item.selectedDecal,
      decalPosition: item.decalPosition,
      rotationY: item.rotationY,
      ripples: item.ripples,
    },
    // pricePerUnit: 29.99, // Add if you have pricing
  }));

  const totalQuantity = orderItems.reduce(
    (sum, item) => sum + item.quantity,
    0
  );

  // Calculate total price (if you have pricing)
  // const totalPrice = orderItems.reduce(
  //   (sum, item) => sum + (item.pricePerUnit || 0) * item.quantity,
  //   0
  // );

  return {
    items: orderItems,
    totalQuantity,
    // totalPrice,
    status: "pending",
  };
}

// =====================================================
// BACKEND API CALLS
// =====================================================

/**
 * Create order in backend (saves to database)
 */
export async function createOrder(order: Order): Promise<string> {
  console.log("📤 Sending order to backend:", order);

  const response = await fetch(`${BASE_URL}/orders`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(order),
  });

  if (!response.ok) {
    throw new Error(`Failed to create order: ${response.statusText}`);
  }

  const data = await response.json();
  console.log("✅ Order created:", data);
  return data.orderId; // Backend returns order ID
}

/**
 * Create Stripe checkout session (backend handles Stripe API)
 */
export async function createCheckoutSession(
  orderId: string,
  customerEmail?: string
): Promise<CheckoutSessionResponse> {
  console.log("💳 Creating Stripe checkout session for order:", orderId);

  const response = await fetch(`${BASE_URL}/checkout/create-session`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      orderId,
      customerEmail,
      // Backend will fetch order details and create Stripe session
    }),
  });

  if (!response.ok) {
    throw new Error(`Failed to create checkout session: ${response.statusText}`);
  }

  const data = await response.json();
  console.log("✅ Checkout session created:", data);
  return data;
}

/**
 * Get order status
 */
export async function getOrderStatus(orderId: string): Promise<Order> {
  const response = await fetch(`${BASE_URL}/orders/${orderId}`);

  if (!response.ok) {
    throw new Error(`Failed to fetch order: ${response.statusText}`);
  }

  return response.json();
}

/**
 * Verify payment completion (webhook alternative)
 */
export async function verifyPayment(orderId: string): Promise<boolean> {
  const response = await fetch(`${BASE_URL}/orders/${orderId}/verify-payment`);

  if (!response.ok) {
    return false;
  }

  const data = await response.json();
  return data.paid === true;
}

// =====================================================
// COMPLETE CHECKOUT FLOW
// =====================================================

/**
 * Complete checkout flow:
 * 1. Prepare order from cart
 * 2. Create order in backend
 * 3. Create Stripe checkout session
 * 4. Redirect to Stripe checkout
 * 5. Clear cart on success
 */
export async function proceedToCheckout(
  customerEmail?: string
): Promise<void> {
  try {
    console.log("🛒 Starting checkout process...");

    // Step 1: Prepare order from cart
    const order = prepareOrderFromCart();

    if (order.items.length === 0) {
      throw new Error("Cart is empty");
    }

    console.log("📦 Order prepared:", order);

    // Step 2: Create order in backend (saves to DB)
    const orderId = await createOrder(order);
    console.log("✅ Order created with ID:", orderId);

    // Step 3: Create Stripe checkout session
    const { checkoutUrl, sessionId } = await createCheckoutSession(
      orderId,
      customerEmail
    );
    console.log("💳 Checkout session created:", sessionId);

    // Step 4: Store order ID in localStorage (for post-payment redirect)
    localStorage.setItem("pendingOrderId", orderId);

    // Step 5: Redirect to Stripe Checkout
    console.log("🔄 Redirecting to Stripe Checkout...");
    window.location.href = checkoutUrl;

    // Cart will be cleared after successful payment (on return from Stripe)
  } catch (error) {
    console.error("❌ Checkout failed:", error);
    throw error;
  }
}

/**
 * Handle return from Stripe (success page)
 * Call this on your success page
 */
export async function handlePaymentSuccess(): Promise<void> {
  const orderId = localStorage.getItem("pendingOrderId");

  if (!orderId) {
    console.warn("⚠️ No pending order found");
    return;
  }

  try {
    // Verify payment completed
    const isPaid = await verifyPayment(orderId);

    if (isPaid) {
      console.log("✅ Payment verified! Clearing cart...");

      // Clear cart
      cartState.items = [];

      // Clear pending order
      localStorage.removeItem("pendingOrderId");

      console.log("🎉 Order completed successfully!");
    } else {
      console.warn("⚠️ Payment not confirmed yet");
    }
  } catch (error) {
    console.error("❌ Failed to verify payment:", error);
  }
}

/**
 * Handle return from Stripe (cancel page)
 */
export function handlePaymentCancel(): void {
  console.log("❌ Payment cancelled by user");
  // Order still exists in backend, cart still has items
  // User can retry checkout
}

// =====================================================
// UPDATE ITEM QUANTITY (SYNC WITH BACKEND OPTIONAL)
// =====================================================

/**
 * Update quantity and optionally sync with backend
 */
export async function updateItemQuantity(
  itemId: string,
  quantity: number,
  syncWithBackend = false
): Promise<void> {
  const itemIndex = cartState.items.findIndex((item) => item.id === itemId);

  if (itemIndex === -1) {
    throw new Error("Item not found");
  }

  const newQuantity = Math.max(1, quantity);
  (cartState.items[itemIndex] as any).quantity = newQuantity;

  console.log(`📝 Updated item ${itemId} quantity to ${newQuantity}`);

  // Optionally sync with backend (for persistent cart)
  if (syncWithBackend) {
    try {
      await fetch(`${BASE_URL}/cart/${itemId}`, {
        method: "PATCH",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ quantity: newQuantity }),
      });
      console.log("✅ Quantity synced with backend");
    } catch (error) {
      console.error("❌ Failed to sync quantity with backend:", error);
    }
  }
}

// =====================================================
// UTILITY FUNCTIONS
// =====================================================

/**
 * Get total item count (including quantities)
 */
export function getTotalItemCount(): number {
  return cartState.items.reduce((total, item) => {
    return total + ((item as any).quantity || 1);
  }, 0);
}

/**
 * Calculate total price (if you have pricing)
 */
export function calculateTotalPrice(pricePerItem = 29.99): number {
  return cartState.items.reduce((total, item) => {
    const quantity = (item as any).quantity || 1;
    return total + pricePerItem * quantity;
  }, 0);
}

/**
 * Clear cart (after successful order)
 */
export function clearCart(): void {
  cartState.items = [];
  console.log("🧹 Cart cleared");
}