// OrderService.ts - Complete order and payment flow for ALL product types
import { cartState, CartItemState, ClothesCartItem, SampleCartItem, PackCartItem } from "../state";

const BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:8080/api";

// =====================================================
// ORDER DATA TYPES
// =====================================================

// Base order item
type BaseOrderItem = {
  productId: string;
  productType: 'clothes' | 'sample' | 'pack';
  quantity: number;
  pricePerUnit?: number;
};

// Clothes order item
export type ClothesOrderItem = BaseOrderItem & {
  productType: 'clothes';
  customization: {
    color: string;
    decal: string;
    decalPosition: [number, number, number] | null;
    rotationY: number;
    ripples: { id: number; pos: [number, number, number] }[];
    selected_type: string;
  };
};

// Sample order item
export type SampleOrderItem = BaseOrderItem & {
  productType: 'sample';
  name: string;
  artist?: string;
  genre?: string;
  bpm?: number;
  key?: string;
  url?: string;
};

// Pack order item
export type PackOrderItem = BaseOrderItem & {
  productType: 'pack';
  name: string;
  artist?: string;
  sampleCount?: number;
  genres?: string[];
};

// Discriminated union of all order item types
export type OrderItem = ClothesOrderItem | SampleOrderItem | PackOrderItem;

export type Order = {
  orderId?: string; // Generated by backend
  items: OrderItem[];
  totalQuantity: number;
  totalPrice: number;
  customerInfo?: {
    email?: string;
    name?: string;
  };
  status: "pending" | "processing" | "completed" | "failed";
  createdAt?: string;
  paymentIntentId?: string; // Stripe payment intent ID
};

export type CheckoutSessionResponse = {
  sessionId: string;
  checkoutUrl: string;
  orderId: string;
};

// =====================================================
// PREPARE ORDER FROM CART
// =====================================================

/**
 * Converts cart items to order format
 * Handles all product types: clothes, samples, packs
 */
export function prepareOrderFromCart(): Order {
  const orderItems: OrderItem[] = cartState.items.map((item): OrderItem => {
    // Common fields
    const quantity = item.quantity || 1;

    // Handle different item types
    switch (item.type) {
      case 'clothes':
        return {
          productId: item.id,
          productType: 'clothes',
          quantity,
          customization: {
            color: item.selectedColor,
            decal: item.selectedDecal,
            decalPosition: item.decalPosition,
            rotationY: item.rotationY,
            ripples: item.ripples,
            selected_type: item.selected_type,
          },
          pricePerUnit: 29.99, // Default clothes price
        };

      case 'sample':
        return {
          productId: item.id,
          productType: 'sample',
          quantity,
          name: item.name,
          artist: item.artist,
          genre: item.genre,
          bpm: item.bpm,
          key: item.key,
          url: item.url,
          pricePerUnit: item.price,
        };

      case 'pack':
        return {
          productId: item.id,
          productType: 'pack',
          quantity,
          name: item.name,
          artist: item.artist,
          sampleCount: item.sampleCount,
          genres: item.genres,
          pricePerUnit: item.price,
        };

      default:
        // TypeScript ensures this never happens
        const _exhaustive: never = item;
        throw new Error(`Unknown item type: ${(_exhaustive as any).type}`);
    }
  });

  const totalQuantity = orderItems.reduce(
    (sum, item) => sum + item.quantity,
    0
  );

  // Calculate total price
  const totalPrice = orderItems.reduce(
    (sum, item) => sum + (item.pricePerUnit || 0) * item.quantity,
    0
  );

  return {
    items: orderItems,
    totalQuantity,
    totalPrice,
    status: "pending",
  };
}

// =====================================================
// BACKEND API CALLS
// =====================================================

/**
 * Create order in backend (saves to database)
 */
export async function createOrder(order: Order): Promise<string> {
  console.log("📤 Sending order to backend:", order);

  const response = await fetch(`${BASE_URL}/orders`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(order),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Failed to create order: ${response.statusText} - ${errorText}`);
  }

  const data = await response.json();
  console.log("✅ Order created:", data);
  return data.orderId; // Backend returns order ID
}

/**
 * Create Stripe checkout session (backend handles Stripe API)
 */
export async function createCheckoutSession(
  orderId: string,
  customerEmail?: string
): Promise<CheckoutSessionResponse> {
  console.log("💳 Creating Stripe checkout session for order:", orderId);

  const response = await fetch(`${BASE_URL}/checkout/create-session`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      orderId,
      customerEmail,
      // Backend will fetch order details and create Stripe session
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Failed to create checkout session: ${response.statusText} - ${errorText}`);
  }

  const data = await response.json();
  console.log("✅ Checkout session created:", data);
  return data;
}

/**
 * Get order status
 */
export async function getOrderStatus(orderId: string): Promise<Order> {
  const response = await fetch(`${BASE_URL}/orders/${orderId}`);

  if (!response.ok) {
    throw new Error(`Failed to fetch order: ${response.statusText}`);
  }

  return response.json();
}

/**
 * Verify payment completion (webhook alternative)
 */
export async function verifyPayment(orderId: string): Promise<boolean> {
  const response = await fetch(`${BASE_URL}/orders/${orderId}/verify-payment`);

  if (!response.ok) {
    return false;
  }

  const data = await response.json();
  return data.paid === true;
}

// =====================================================
// COMPLETE CHECKOUT FLOW
// =====================================================

/**
 * Complete checkout flow:
 * 1. Prepare order from cart
 * 2. Create order in backend
 * 3. Create Stripe checkout session
 * 4. Redirect to Stripe checkout
 * 5. Clear cart on success
 */
export async function proceedToCheckout(
  customerEmail?: string
): Promise<void> {
  try {
    console.log("🛒 Starting checkout process...");

    // Step 1: Prepare order from cart
    const order = prepareOrderFromCart();

    if (order.items.length === 0) {
      throw new Error("Cart is empty");
    }

    console.log("📦 Order prepared:", order);
    console.log(`   - ${order.items.filter(i => i.productType === 'clothes').length} clothes items`);
    console.log(`   - ${order.items.filter(i => i.productType === 'sample').length} sample items`);
    console.log(`   - ${order.items.filter(i => i.productType === 'pack').length} pack items`);
    console.log(`   - Total: $${order.totalPrice.toFixed(2)}`);

    // Step 2: Create order in backend (saves to DB)
    const orderId = await createOrder(order);
    console.log("✅ Order created with ID:", orderId);

    // Step 3: Create Stripe checkout session
    const { checkoutUrl, sessionId } = await createCheckoutSession(
      orderId,
      customerEmail
    );
    console.log("💳 Checkout session created:", sessionId);

    // Step 4: Store order ID in localStorage (for post-payment redirect)
    localStorage.setItem("pendingOrderId", orderId);

    // Step 5: Redirect to Stripe Checkout
    console.log("🔄 Redirecting to Stripe Checkout...");
    window.location.href = checkoutUrl;

    // Cart will be cleared after successful payment (on return from Stripe)
  } catch (error) {
    console.error("❌ Checkout failed:", error);
    throw error;
  }
}

/**
 * Handle return from Stripe (success page)
 * Call this on your success page
 */
export async function handlePaymentSuccess(): Promise<void> {
  const orderId = localStorage.getItem("pendingOrderId");

  if (!orderId) {
    console.warn("⚠️ No pending order found");
    return;
  }

  try {
    // Verify payment completed
    const isPaid = await verifyPayment(orderId);

    if (isPaid) {
      console.log("✅ Payment verified! Processing order...");

      // Get order details
      const order = await getOrderStatus(orderId);
      
      // Move items to purchase history
      const purchasedItems = cartState.items.map(item => ({ ...item }));
      cartState.purchaseHistory.push(...purchasedItems);

      // Clear cart
      cartState.items = [];

      // Clear pending order
      localStorage.removeItem("pendingOrderId");

      console.log("🎉 Order completed successfully!");
      console.log(`   - Order ID: ${orderId}`);
      console.log(`   - Total: $${order.totalPrice.toFixed(2)}`);
    } else {
      console.warn("⚠️ Payment not confirmed yet");
    }
  } catch (error) {
    console.error("❌ Failed to verify payment:", error);
  }
}

/**
 * Handle return from Stripe (cancel page)
 */
export function handlePaymentCancel(): void {
  console.log("❌ Payment cancelled by user");
  // Order still exists in backend, cart still has items
  // User can retry checkout
}

// =====================================================
// CART MANAGEMENT (OPTIONAL - USE cartActions INSTEAD)
// =====================================================

/**
 * Update quantity for any item type
 * @deprecated Use cartActions.updateQuantity() instead
 */
export async function updateItemQuantity(
  itemId: string,
  quantity: number,
  syncWithBackend = false
): Promise<void> {
  const item = cartState.items.find((item) => item.id === itemId);

  if (!item) {
    throw new Error("Item not found");
  }

  const newQuantity = Math.max(1, quantity);
  item.quantity = newQuantity;

  console.log(`📝 Updated item ${itemId} quantity to ${newQuantity}`);

  // Optionally sync with backend (for persistent cart)
  if (syncWithBackend) {
    try {
      await fetch(`${BASE_URL}/cart/${itemId}`, {
        method: "PATCH",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ quantity: newQuantity }),
      });
      console.log("✅ Quantity synced with backend");
    } catch (error) {
      console.error("❌ Failed to sync quantity with backend:", error);
    }
  }
}

// =====================================================
// UTILITY FUNCTIONS
// =====================================================

/**
 * Get total item count (including quantities)
 */
export function getTotalItemCount(): number {
  return cartState.items.reduce((total, item) => {
    return total + (item.quantity || 1);
  }, 0);
}

/**
 * Calculate total price for all items in cart
 */
export function calculateTotalPrice(): number {
  return cartState.items.reduce((total, item) => {
    const quantity = item.quantity || 1;
    
    // Get price based on item type
    let pricePerUnit = 0;
    switch (item.type) {
      case 'clothes':
        pricePerUnit = 29.99; // Default clothes price
        break;
      case 'sample':
        pricePerUnit = item.price;
        break;
      case 'pack':
        pricePerUnit = item.price;
        break;
    }
    
    return total + (pricePerUnit * quantity);
  }, 0);
}

/**
 * Get breakdown of cart by product type
 */
export function getCartBreakdown() {
  const breakdown = {
    clothes: {
      count: 0,
      total: 0,
    },
    samples: {
      count: 0,
      total: 0,
    },
    packs: {
      count: 0,
      total: 0,
    },
  };

  cartState.items.forEach(item => {
    const quantity = item.quantity || 1;
    
    switch (item.type) {
      case 'clothes':
        breakdown.clothes.count += quantity;
        breakdown.clothes.total += 29.99 * quantity;
        break;
      case 'sample':
        breakdown.samples.count += quantity;
        breakdown.samples.total += item.price * quantity;
        break;
      case 'pack':
        breakdown.packs.count += quantity;
        breakdown.packs.total += item.price * quantity;
        break;
    }
  });

  return breakdown;
}

/**
 * Clear cart (after successful order)
 */
export function clearCart(): void {
  cartState.items = [];
  console.log("🧹 Cart cleared");
}

/**
 * Validate cart before checkout
 */
export function validateCart(): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  if (cartState.items.length === 0) {
    errors.push("Cart is empty");
  }

  cartState.items.forEach(item => {
    // Validate quantity
    if (!item.quantity || item.quantity < 1) {
      errors.push(`Invalid quantity for item: ${item.id}`);
    }

    // Type-specific validation
    switch (item.type) {
      case 'clothes':
        if (!item.selectedColor) {
          errors.push(`Missing color for clothes item: ${item.id}`);
        }
        if (!item.selected_type) {
          errors.push(`Missing type for clothes item: ${item.id}`);
        }
        break;
      
      case 'sample':
        if (!item.name || item.price <= 0) {
          errors.push(`Invalid sample data: ${item.id}`);
        }
        break;
      
      case 'pack':
        if (!item.name || item.price <= 0) {
          errors.push(`Invalid pack data: ${item.id}`);
        }
        break;
    }
  });

  return {
    valid: errors.length === 0,
    errors,
  };
}